version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image:  mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=rootuser
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=rootpass
      - ME_CONFIG_BASICAUTH_USERNAME=admin  # Optional: Add web UI authentication
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  # Optional: Add web UI authentication
      - ME_CONFIG_MONGODB_SERVER=mongodb
  # spring-security-jwt:
  #   image: spring-security-jwt:latest # Replace this with the actual image name if you are building the image separately
  #   container_name: spring-security-jwt
  #   build:
  #     context: ./ # Path to the FMS backend project
  #     dockerfile: Dockerfile # Ensure you have a Dockerfile for the Spring Boot app
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - SPRING_DATA_MONGODB_URI=mongodb://rootuser:rootpass@mongodb:27017/?authSource=admin
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
